version: "3.7"
services:
  crawler:
    # build: .
    image: kukker/lightnovel-crawler:latest
    command: ["--bot", "telegram", "TELEGRAM_TOKEN=${TELEGRAM_TOKEN}"]
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
    volumes:
      - /home/pi/Lightnovels:/Lightnovels
    networks:
      - net
networks:
  net:
