name: ARM Docker Image CI

on: [push]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@master
    - name: Login to GitHub Package Repository
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
        GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_PACKAGE_REGISTRY_TOKEN }}
      run: |
        docker login docker.pkg.github.com -u publisher -p "${GITHUB_PACKAGE_REGISTRY_TOKEN}"
        docker pull docker.pkg.github.com/kukkerem/lightnovel-crawler/lightnovel-crawler:arm
    - name: Build the Docker image
      run: docker buildx build --platform=linux/arm/v7 . --file Dockerfile --tag lightnovel-crawler:arm
    - name: Tag latest if master
      if: github.ref == 'refs/heads/master'
      run: |
        # we push latest separate so it shows up as latest in the UI
        docker tag lightnovel-crawler:arm docker.pkg.github.com/kukkerem/lightnovel-crawler/lightnovel-crawler:arm
        docker push docker.pkg.github.com/kukkerem/lightnovel-crawler/lightnovel-crawler:arm
