name: Git upstream update

on:
  schedule:
  #- cron: 0 2 * * *
  - cron:  '*/15 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Update master
      env: 
        GITHUB_TOKEN : ${{ secrets.GITHUB_PUSH_TOKEN }}
      run: |
        git remote set-url origin https://Kukkerem:"${GITHUB_TOKEN}"@github.com/Kukkerem/lightnovel-crawler.git
        git remote add upstream https://github.com/dipu-bd/lightnovel-crawler.git
        git remote update
        git checkout --track origin/master
        git config --global user.email "kukkerem@gmail.com"
        git config --global user.name "Kukkerem"
        git merge upstream/master
        git push | true

